"""empty message

Revision ID: 9b60e4cd73a9
Revises: 1a25a3e0d86e
Create Date: 2022-12-12 07:27:35.254927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b60e4cd73a9'
down_revision = '1a25a3e0d86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_talent',
               existing_type=sa.String(length=11),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
